### PR TITLE
Pattern.simplify() (#9)

### PR DESCRIPTION
**Pull request by Danon**
`PatternSimplifier` can
 - Simplify quantifiers - `{0,1}` -> `?`
 - Change character groups - `[0-9]` -> `\d` (same with `\w`, `\W` and `\D`) regardless of order
 - Change one letter alternation - `(a|b|c)` -> `[abc]`
 - Remove quotes from group `[\.\)]` ->` [.)]`
 - Remove group for one character (escaped if necessary) -> `[?]` -> `\?`

### CODE REVIEW

**Comment by Danon** [comment]
What should be done further:
 - Remove duplicates from group - `[aabbcc]` -> `[abc]`

**Comment by danilopinotti** [comment]
Hi,
I don't read your code, but in description, you said: (a|b|c) -> [abc]
The correct simplification is ([abc]) because the group reference.
Is the code working this way?

**Comment by Danon** [comment]
@danilopinotti Hey, thanks for interest in T-Regx! :)

Of course, you're right! `(a|b|c)` is a capturing group - we can't change it to `[abc]` :/

---
PS: We can change `(?:a|b|c)` to `[abc]`, though :D Although smart person enough to use `(?:` is also smart enough to change it manually.

**Comment by Danon** [comment]
Unfurtunately, as you can see it doesn't work yet. I hoped automatic simplification of patterns would call more people to use T-Regx, but I didn't have time yet to implement it fully. And I want it to be 100% bullet-proff. 95% for me is not enough, so it'll have to wait a bit.

**Comment by danilopinotti** [comment]
I recommend you to cache (in an static private attribute or better way) from simplified pattern because of the amount of processing that is used to generate the result.

**Comment by danilopinotti** [comment]
> Unfurtunately, as you can see it doesn't work yet. I hoped automatic simplification of patterns would call more people to use T-Regx, but I didn't have time yet to implement it fully. And I want it to be 100% bullet-proff. 95% for me is not enough, so it'll have to wait a bit.

When i have time, i'll try to contribute. Actually i work with another lib (only concepts, for a while)

**Comment by Danon** [comment]
Well, if you want to continue my work (or start your own completely) regarding pattern simplification - you're very welcome :) I believe there are some unit tests ready, so you can reuse them.

But no presure, if you don't - I'll fix them. Just a bit later.

**Comment by Danon** [comment]
Actually, as I read my commits - I have already thought about that. If you look at file: test/Integration/TRegx/CleanRegex/Analyze/Simplify/PatternSimplifierTest.php
In this PR, you'll see it's already covered :)

**Pull request closed without merging**
